baseURL = "https://sqpdev.com/"
languageCode = "en-gb"
title = "SQP Dev"
theme = "sqpdev"

[params]
  description = "Infrastructure as Code"
  author = "SQP Dev"
  logo = "/images/logo.png"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"
    lineNos = false

[outputs]
  home = ["HTML", "RSS"]

[sitemap]
  changefreq = "weekly"
  priority = 0.5
